{
  description = "Personal NixOS configs";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    stylix.url = "github:danth/stylix";

    nix-flatpak.url = "github:gmodena/nix-flatpak";

    nixos-cosmic.url = "github:lilyinstarlight/nixos-cosmic";

    nix-darwin = {
      url = "github:LnL7/nix-darwin/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    vscode-server.url = "github:nix-community/nixos-vscode-server";

    lanzaboote = {
      url = "github:nix-community/lanzaboote/v0.4.2";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      home-manager,
      nix-flatpak,
      nixos-cosmic,
      nix-darwin,
      vscode-server,
      stylix,
      lanzaboote,
      disko,
      ...
    }@inputs:
    let
      lib = nixpkgs.lib;
    in
    {
      nixosConfigurations =
        let
          mkNixosConfig =
            name:
            {
              system ? "x86_64-linux",
              useDefaultModules ? true,
              enableHomeManager ? true,
              enableFlatpak ? true,
              enableStylix ? true,
              enableVscodeServer ? false,
              enableLanzaboote ? false,
              enableDisko ? false,
              extraModules ? [ ],
            }:
            nixpkgs.lib.nixosSystem {
              specialArgs = { inherit inputs; };
              inherit system;
              modules = [
                ./hosts/${name}/configuration.nix
              ]
              ++ lib.optionals enableHomeManager [
                home-manager.nixosModules.home-manager
                {
                  home-manager.extraSpecialArgs = {
                    inherit inputs;
                  };
                  home-manager.useGlobalPkgs = true;
                  home-manager.useUserPackages = true;
                  home-manager.users.jade = {
                    imports = [
                      ./hosts/${name}/home.nix
                    ];
                  };
                  home-manager.backupFileExtension = "backup";
                }
              ]
              ++ lib.optional useDefaultModules ./modules
              ++ lib.optional enableFlatpak nix-flatpak.nixosModules.nix-flatpak
              ++ lib.optional enableStylix stylix.nixosModules.stylix
              ++ lib.optional enableVscodeServer vscode-server.nixosModules.default
              ++ lib.optional enableLanzaboote lanzaboote.nixosModules.lanzaboote
              ++ lib.optional enableDisko disko.nixosModules.default
              ++ extraModules;
            };
        in
        {
          desktop = mkNixosConfig "desktop" { enableLanzaboote = true; };
          game-servers = mkNixosConfig "game-servers" { enableVscodeServer = true; };
          media = mkNixosConfig "media" { enableVscodeServer = true; };
          mediapi = mkNixosConfig "mediapi" {
            system = "aarch64-linux";
            enableFlatpak = false;
            enableDisko = true;
            extraModules = [
              ./hosts/mediapi/hardware-configuration.nix # Generated by nixos-anywhere
            ];
          };
          /*
            Cosmic stuff is adapted from FelixSchausberger's Cosmic configuration
            https://github.com/FelixSchausberger/nixos
          */
          t480 = mkNixosConfig "t480" {
            extraModules = [
              {
                nix.settings = {
                  substituters = [ "https://cosmic.cachix.org/" ];
                  trusted-public-keys = [ "cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=" ];
                };
              }
              nixos-cosmic.nixosModules.default
            ];
          };
        };

      # MacBook configuration
      darwinConfigurations."macbook" = nix-darwin.lib.darwinSystem {
        specialArgs = { inherit inputs; };
        modules = [
          ./hosts/macbook/configuration.nix
          # stylix.nixosModules.stylix
          # nix-flatpak.nixosModules.nix-flatpak
          # home-manager.nixosModules.home-manager
          # {
          #   home-manager.extraSpecialArgs = { inherit inputs; };
          #   home-manager.useGlobalPkgs = true;
          #   home-manager.useUserPackages = true;
          #   home-manager.users.jade = {
          #     imports = [
          #       ./hosts/macbook/home.nix
          #     ];
          #   };
          #   home-manager.backupFileExtension = "backup";
          # }
        ];
      };

      homeModules.default = ./modules/home;
    };
}
